import { createHash } from 'crypto';
// @ts-expect-error — paytmchecksum ships no type declarations.
import PaytmChecksum from 'paytmchecksum';
import { verifyPaytmSignature, verifyPhonePeSignature } from './verify-webhook-signature.util';

// Section 8A.3 — real crypto round-trips (not mocked), since these are the
// one place a subtly-wrong hash/checksum implementation would silently
// accept forged money-touching payloads. CLAUDE.md: webhook handlers must
// be signature-verified.
describe('verifyPhonePeSignature', () => {
  const username = 'dealer-user';
  const password = 'dealer-pass';

  function sign(user: string, pass: string): string {
    return createHash('sha256').update(`${user}:${pass}`).digest('hex');
  }

  it('accepts a correctly computed Authorization header', () => {
    expect(verifyPhonePeSignature(sign(username, password), username, password)).toBe(true);
  });

  it('rejects a header signed with the wrong password', () => {
    expect(
      verifyPhonePeSignature(sign(username, 'wrong-pass'), username, password),
    ).toBe(false);
  });

  it('rejects a missing header', () => {
    expect(verifyPhonePeSignature(undefined, username, password)).toBe(false);
  });

  it('fails closed when credentials are not configured', () => {
    expect(verifyPhonePeSignature(sign(username, password), undefined, undefined)).toBe(false);
  });
});

describe('verifyPaytmSignature', () => {
  // Real Paytm merchant keys are always exactly 16 characters — the
  // package's AES-128-CBC encryption requires a 16-byte key and throws
  // otherwise (RangeError: Invalid key length), confirmed empirically
  // against node_modules/paytmchecksum/PaytmChecksum.js. See
  // update-upi-capture-config.dto.ts's @Length(16, 16) on paytmMerchantKey.
  const merchantKey = 'testmerchantkey1';

  it('accepts a checksum generated by Paytm\'s own generateSignature for these params', async () => {
    const params = { ORDERID: 'order-1', TXNAMOUNT: '500.00', STATUS: 'TXN_SUCCESS' };
    const checksum: string = await PaytmChecksum.generateSignature(params, merchantKey);

    expect(verifyPaytmSignature({ ...params, CHECKSUMHASH: checksum }, merchantKey)).toBe(true);
  });

  it('rejects a checksum generated with a different merchant key', async () => {
    const params = { ORDERID: 'order-1', TXNAMOUNT: '500.00', STATUS: 'TXN_SUCCESS' };
    const checksum: string = await PaytmChecksum.generateSignature(params, 'adifferentkey123');

    expect(verifyPaytmSignature({ ...params, CHECKSUMHASH: checksum }, merchantKey)).toBe(false);
  });

  it('rejects a body with a tampered field after signing', async () => {
    const params = { ORDERID: 'order-1', TXNAMOUNT: '500.00', STATUS: 'TXN_SUCCESS' };
    const checksum: string = await PaytmChecksum.generateSignature(params, merchantKey);

    expect(
      verifyPaytmSignature(
        { ORDERID: 'order-1', TXNAMOUNT: '999999.00', STATUS: 'TXN_SUCCESS', CHECKSUMHASH: checksum },
        merchantKey,
      ),
    ).toBe(false);
  });

  it('rejects a missing CHECKSUMHASH', () => {
    expect(verifyPaytmSignature({ ORDERID: 'order-1' }, merchantKey)).toBe(false);
  });

  it('fails closed when merchantKey is not configured', async () => {
    const params = { ORDERID: 'order-1' };
    const checksum: string = await PaytmChecksum.generateSignature(params, merchantKey);

    expect(
      verifyPaytmSignature({ ...params, CHECKSUMHASH: checksum }, undefined),
    ).toBe(false);
  });
});
